### PR TITLE
Add activerecord version for Rails 5

### PR DESCRIPTION
**Pull request by eszarpa**
To upgrade goose, TM needs this update

### CODE REVIEW

**Comment by chappieweb** [comment]
I probably don’t need to be on this distribution any longer.

Joe

On Oct 5, 2018, at 12:45 PM, Tommy Lee Stokes <notifications@github.com<mailto:notifications@github.com>> wrote:



@tstokes approved this pull request.

**Comment by eszarpa** [comment]
@arparker @tstokes - deploy request

**Comment by tstokes** [comment]
Approved

**Comment by arparker** [comment]
Approved

**Pull request merged**
